config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  resources :create_jobs

  resources :applies
    root            to: 'static_pages#index'
    get 'about',    to: 'static_pages#about'
    get 'contact',  to: 'static_pages#contact'
    get 'our',      to: 'static_pages#our'
    get 'famous',      to: 'static_pages#famous'
    get 'enter',    to: 'sessions#new'
    post 'enter',   to: 'sessions#create'
    delete 'exit',  to: 'sessions#destroy'
    resources :create_jobs
       resources :applies
    resources :users, only: [:new, :create, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/apply.rb
class Apply < ApplicationRecord
    validates :name, presence: true, length: { maximum: 50 }
    validates :age, presence: true, length: { maximum: 3 }
    validates :position, presence: true, length: { maximum: 50 }
    validates :phone, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 50 }
    
end

app/models/create_job.rb
class CreateJob < ApplicationRecord
    validates :name, presence: true, length: { maximum: 50 }
    validates :position, presence: true, length: { maximum: 50 }
    validates :position, presence: true, length: { maximum: 50 }
    validates :annual_salary, presence: true, length: { maximum: 50 }
    validates :contract_time, presence: true, length: { maximum: 50 }

end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password

 
  
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  
    validates :name, presence: true, length: { maximum: 50 }
    validates :password, length: { minimum: 6 }
    validates :email, presence: true, length: { maximum: 255 },
                                      format: { with: VALID_EMAIL_REGEX },
                                      uniqueness: { case_sensitive: true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception

    include SessionsHelper
end

app/controllers/applies_controller.rb
class AppliesController < ApplicationController
  before_action :set_apply, only: [:show, :edit, :update, :destroy]

  # GET /applies
  # GET /applies.json
  def index
    @applies = Apply.all
  end

  # GET /applies/1
  # GET /applies/1.json
  def show
  end

  # GET /applies/new
  def new
    @apply = Apply.new
  end

  # GET /applies/1/edit
  def edit
  end

  # POST /applies
  # POST /applies.json
  def create
    @apply = Apply.new(apply_params)

    respond_to do |format|
      if @apply.save
        format.html { redirect_to @apply, notice: 'Apply was successfully created.' }
        format.json { render :show, status: :created, location: @apply }
      else
        format.html { render :new }
        format.json { render json: @apply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applies/1
  # PATCH/PUT /applies/1.json
  def update
    respond_to do |format|
      if @apply.update(apply_params)
        format.html { redirect_to @apply, notice: 'Apply was successfully updated.' }
        format.json { render :show, status: :ok, location: @apply }
      else
        format.html { render :edit }
        format.json { render json: @apply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applies/1
  # DELETE /applies/1.json
  def destroy
    @apply.destroy
    respond_to do |format|
      format.html { redirect_to applies_url, notice: 'AAre you sure you want to delete.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apply
      @apply = Apply.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def apply_params
      params.require(:apply).permit(:name, :age, :position, :phone, :string, :email, )
    end
end

app/controllers/create_jobs_controller.rb
class CreateJobsController < ApplicationController
  before_action :set_create_jobs, only: [:show, :edit, :update, :destroy]

  # GET /create_jobs
  # GET /create_jobs.json
  def index
    @create_jobs = CreateJob.all
  end

  # GET /create_jobs/1
  # GET /create_jobs/1.json
  def show
  end

  # GET /create_jobs/new
  def new
    @create_job = CreateJob.new
  end


  # GET /create_jobs/1/edit
  def edit
  end

  # POST /create_jobs
  # POST /create_jobs.json
  def create
    @create_job = CreateJob.new(create_job_params)

    respond_to do |format|
      if @create_job.save
        format.html { redirect_to @create_job, notice: 'Create job was successfully created.' }
        format.json { render :show, status: :created, location: @create_job }
      else
        format.html { render :new }
        format.json { render json: @create_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /create_jobs/1
  # PATCH/PUT /create_jobs/1.json
  def update
    respond_to do |format|
      if  @create_job.update(create_job_params)
        format.html { redirect_to @create_job, notice: 'job was successfully updated.' }
        format.json { render :show, status: :ok, location: @create_job }
      else
        format.html { render :edit }
        format.json { render json: @create_job.errors, status: :unprocessable_entity }
      end
    end
  end
  


  # DELETE /create_jobs/1
  # DELETE /create_jobs/1.json
  def destroy
    @create_job.destroy
    respond_to do |format|
      format.html { redirect_to create_jobs_url, notice: 'Create job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_create_jobs
    @create_job = CreateJob.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def create_job_params
    params.require(:create_job).permit(:name, :position, :annual_salary, :contract_time)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to user_path(current_user) if user_signed_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      redirect_to user_path(current_user)
    else
      flash.now[:danger] = 'Invalid email and password'
      render 'new'
    end
  end

  def destroy
    sign_out
    flash[:success] = 'Successful logout'
    redirect_to enter_path
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def index
        @name = "LEO"
    end
    def about
    end 

def contact
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      flash[:success] = 'Congratulations successful registration'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applies_helper.rb
module AppliesHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/create_jobs_helper.rb
module CreateJobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(user)
      session[:user_id] = user.id
    end
  
    def sign_out
      session.delete(:user_id)
    end
  
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
  
    def user_signed_in?
      !current_user.nil?
    end
  
  end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/applies/_form.html.erb
<%= form_with(model: apply, local: true) do |form| %>
  <% if apply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apply.errors.count, "error") %> prohibited this apply from being saved:</h2>

      <ul>
      <% apply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>



  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/applies/edit.html.erb
<h1>Editing Apply</h1>

<%= render 'form', apply: @apply %>

<%= link_to 'Show', @apply %> |

<%= link_to 'Back',  @apply %>

app/views/applies/index.html.erb
<div class="row">
  <div class="col-xs-12 text-center">
    <h1>My applyes</h1>
    <br> <br>
  </div>

  <div class="col-md-8 col-md-offset-2 col-xs-12">
    <table class="table table-striped">
      <thead>
        <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Position</th>
      <th>Phone</th>
        <th>email</th>

         <th colspan="3"></th>
      <h2><strong> Management applies</strong></h2> 
      <td><%= link_to 'New aplly',  new_apply_path(current_user), class: 'btn btn-success'%></td>
            <td> <%= link_to 'back', user_path(current_user), class: 'btn btn-success'%></td>
            
          </th>
        </tr> 
          <th colspan="5">

      <tbody>
        <% if @applies.empty? %>
          <tr>
            <td colspan="3" class="text-center">
              <h3>No registered applications.</h3>
              <%= link_to 'click here', new_apply_path(current_user) %> to register a new application
            </td>
          </tr>
        <% end %>
        <% @applies.each do |c| %>
        <tr>
          <td>
            <%= c.name %>
          </td>
          <td>
            <%= c.age %>
          </td>
           <td>
            <%= c.position %>
          </td>
          <td>
            <%= c.phone %>
          </td>
          <td>
            <%= c.email %>
          </td>
          <td>
            <%= link_to 'Edit', edit_apply_path(c), class: 'btn btn-warning' %>
          </td>
          <td>
            <%= link_to 'Destroy', apply_path(c), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete' } %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/applies/new.html.erb
<h1>Player/staff registration</h1>

<%= render 'form', apply: @apply %>

<%= link_to 'Back', root_url %>

app/views/applies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @apply.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @apply.age %>
</p>

<p>
  <strong>Position:</strong>
  <%= @apply.position %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @apply.phone %>
</p>



<p>
  <strong>Email:</strong>
  <%= @apply.email %>
</p>



<%= link_to 'Edit', edit_apply_path(@apply) %> |
<%= link_to 'Back', root_url  %>

app/views/create_jobs/_form.html.erb
<%= form_with(model: create_job, local: true) do |form| %>
  <% if create_job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(create_job.errors.count, "error") %> prohibited this create_job from being saved:</h2>

      <ul>
      <% create_job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div>

  <div class="field">
    <%= form.label :annual_salary %>
    <%= form.text_field :annual_salary %>
  </div>

  <div class="field">
    <%= form.label :contract_time %>
    <%= form.text_field :contract_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/create_jobs/edit.html.erb
<h1>Editing Create Job</h1>

<%= render 'form', create_job: @create_job %>

<%= link_to 'Show', @create_job %> |
<%= link_to 'Back', @create_job %>

app/views/create_jobs/index.html.erb
<div class="row">
  <div class="col-xs-12 text-center">
    <h1>Create jobs</h1>
    <br> <br>
  </div>


  <div class="col-md-8 col-md-offset-2 col-xs-12">
    <table class="table table-striped">
      <thead>
        <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Annual salary</th>
      <th>Contract time</th>
      <th colspan="3"></th>
     <h2><strong> Management Jobs</strong></h2> 

    <td><%= link_to 'New jobs',  new_create_job_path(current_user), class: 'btn btn-success'%></td>
          <td> <%= link_to 'back', user_path(current_user), class: 'btn btn-success'%></td>
            
          </th>
        </tr> 
      </thead>

  <tbody>
   <% if@create_jobs.empty? %>
      <tr>
    <td colspan="4" class="text-center">
              <h3>No registered applications.</h3>
              <%= link_to 'click here', create_jobs_path(current_user) %> to register a new  job application
            </td>
          </tr>
        <% end %>
 <% @create_jobs.each do |c| %>
<tr>
          <td>
            <%= c.name %>
          </td>
          <td>
            <%= c.position %>
          </td>
           <td>
            <%= c.annual_salary %>
          </td>
          <td>
            <%= c.contract_time %>
          </td>
          <td>
            <%= link_to 'Edit', edit_create_job_path(c),  :class => 'btn btn-warning' %>
          </td>
          <td>
            <%= link_to 'Destroy', create_job_path(c), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete?' } %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

        

app/views/create_jobs/new.html.erb
<h1>New Create Job</h1>

<%= render 'form', create_job: @create_job %>


<%= link_to 'Back', root_url %>

app/views/create_jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @create_job.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @create_job.position %>
</p>

<p>
  <strong>Annual salary:</strong>
  <%= @create_job.annual_salary %>
</p>

<p>
  <strong>Contract time:</strong>
  <%= @create_job.contract_time %>
</p>

<%= link_to 'Edit', edit_create_job_path(@create_job) %> |
<%= link_to 'Back', root_url %>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="">
    <div class="alert alert-danger">
      Ops! We Found <%= pluralize(object.errors.count, 'error', 'errors') %>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <%= link_to 'Soccer Agency.    @Copyrigth', root_path %>
  </small>

  <nav>
    <ul>
      <li>
        <%= link_to 'About Us', about_path %>
      </li>
      <li>
        <%= link_to 'Contacts Us', contact_path %>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">

  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu" aria-expanded=" false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
          
        
      </button>
 
    </div>

  <div class="collapse navbar-collapse" id="expanded-menu">
    <ul class="nav navbar-nav">
      <% if !user_signed_in? %>
        <li class="active">   
       
      </li>
      <% end %>
  <li class="active">
        <%= link_to 'Home ', root_url %>
      </li>
      <li class="active">
        <%= link_to 'About Us', about_path %>
      </li>

          <li class="active">
          <%= link_to 'Contacts Us', contact_path %>
  </li>

          <li class="active">
          <%= link_to 'New Register', new_user_path %>
  </li>
   </li>

          <li class="active">
          <%= link_to 'Our History', our_path %>
  </li>
   </li>

          <li class="active">
          <%= link_to 'Our main players', famous_path %>
  </li>


    </ul>

   <ul class="nav navbar-nav navbar-right">

      <% if !user_signed_in? %>
        <li>
          <%= link_to 'login', enter_path %>
      </li>
      <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
           Welcome, <%= current_user.name %> <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
               <%= link_to 'My page', current_user %>
            </li>
            <li>
          
            </li>
            <li class="divider" role="separator"></li>
            <li>
              <%= link_to 'logout', exit_path, method: :delete %>
            </li>
          </ul>
        </li>
      <% end %>

    </ul>

  </div>

  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Soccer Agency</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <%= render 'layouts/header' %>

   <div class="container">

     <% flash.each do |message_type, message| %>
       <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
         <button type="button" class="close" data-dismiss="alert" aria-label="Close">
           <span aria-hidden="true">&times;</span>
         </button>
         <%= message %>
       <% end %>
     <% end %>

     <%= yield %>

     <%= render 'layouts/footer' %>
   </div>


 </body>
</html>

app/views/static_pages/about.html.erb
<h1>About Us </h1>
<br><br>

<p>
  Created with the aim of revolutionizing the sports market, we will become the largest database of football athletes in the world. We connect with the Top Clubs in the world and help to find new football stars. We work with ethics, respect and care for the image of our clients.
</p>

app/views/static_pages/contact.html.erb
<h1>Contact us</h1>

<strong>Australia<strong>
<p>155 king ST, NSW</p>
<p>Phone: +61 55555555</p>
<a href="mailto:someone@example.com?subject=Questions" title="">soccer.agency@email.com</a>

<br><br>



<strong>England<strong>
<p>155 Queen ST, Buckingham</p>
<p>Phone: +44 6666666</p>
<a href="mailto:someone@example.com?subject=Questions" title="">soccer.agency@email.com</a>
<br><br>

<strong>New Zeland<strong>
<p>155 Princess ST, Haka</p>
<p>Phone: +64 6666666</p>
<a href="mailto:someone@example.com?subject=Questions" title="">soccer.agency@email.com</a>
<br><br>

<strong>Brazil<strong>
<p>155 Maria ST, Sao Paulo </p>
<p>Phone: +55 6666666</p>
<a href="mailto:someone@example.com?subject=Questions" title="">soccer.agency@email.com</a>

<br>


   <a href="https://www.linkedin.com/in/leolasz/">

app/views/static_pages/famous.html.erb
<h1>Our main players </h1>
<br><br>

-  Cristiano ronaldo <br>
-  Lionel Messi<br>
-  Luiz Suarez<br>
-  Lionel Messi<br>
-	Kylian Mbappé<br>
-  Eden Hazard  <br>

app/views/static_pages/index.html.erb
<div class="jumbotron">
  <h1>Soccer Agency</h1>
<p> The best place for players and clubs to connect </p>
  <br> <br>  <br>  <br>  <br>  <br>  

    <%= link_to 'Player Registration / Staff Registration', new_apply_path, class: 'btn btn-primary btn-lg' %>
    
  <%= link_to 'Club Registration', new_create_job_path, class: 'btn btn-primary btn-lg' %>
  <%= link_to 'new Registration', new_user_path, class: 'btn btn-primary btn-lg' %>
  </p>
</div>

app/views/static_pages/our.html.erb
<h1>Our History </h1>
<br><br>

<p>
  Our founder, Leonardo Souza, was born in Brazil, and since he was 7 years old he started playing competitions, where he was called up by the national team SUB15 and during his career he played in several clubs such as Santos FC, Internacional and Palmeiras. Upon retiring he decided to create the largest company for jobs for athletes and technical commission in the world.

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Register now</h1>
  </div>

    <div class="col-md-6 col-md-offset-3 col-xs-12">
<%=  form_for @user do |f|  %>
   <%= render 'layouts/error_messages', object: f.object %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit 'Register', class: 'btn btn-primary' %>
  <% end %>
  </div>
  </div>

app/views/users/show.html.erb
<h2>Hello <%= current_user.name %> </h2>

<br>
  <strong>Welcome to manager site:</strong>

<br><br><br><br><br>


  <span><button type="button" class="btn btn-danger"><%= link_to 'Player Applications', applies_path %></button></span>
<button type="button" class="btn btn-warning"><%= link_to 'Club Applications', create_jobs_path %></button>
<button type="button" class="btn btn-success"> <%= link_to 'New register Manage', new_user_path %></button>
<button type="button" class="btn btn-info"><%= link_to 'Home Page', root_url %></button>
<br><br><br><br><br>